version: '3.4'

services:

  proxy:
    container_name: proxy
    image: encircle/nginx-proxy:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./gunicorn:/var/run/gunicorn
    restart: unless-stopped
    networks:
      - proxy
    environment:
      SITE: localhost
      MODSEC_ENGINE_MODE: 'On'
      ENDPOINT: https://clamd

  clamd:
    container_name: clamd
    image: encircle/restingclam:latest
    volumes:
      - ./gunicorn:/var/run/gunicorn
      - ./logs:/var/log/clamav
    networks:
      - av
    restart: unless-stopped

networks:
  proxy:
  av:
