version: '3.5'

services:

  postfix:
    container_name: postfix
    image: encircle/postfix:v1.0.15
    restart: unless-stopped
    networks:
      - mail
    environment:
      HOSTNAME: postfix

networks:
  mail:
    name: postfixversion: '3.5'

services:

  postfix:
    container_name: postfix
    image: encircle/postfix:v1.0.15
    restart: unless-stopped
    networks:
      - mail
    environment:
      HOSTNAME: postfix

networks:
  mail:
    name: postfix
