version: '3.4'

services:

  webserver:
    container_name: webserver
    image: encircle/nginx-modsec:latest
    ports:
      - '5.153.254.26:80:80'
      - '5.153.254.26:443:443'
    depends_on:
      - wordpress
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./wordpress/:/var/www/html
      - ./nginx/certs/:/etc/nginx/certs
    restart: unless-stopped
    networks:
      - frontend
    environment:
      ENV: ${ENV}
      FPM_HOST: ${FPM_HOST}
      SITE: ${SITE}
      LETSENCRYPT: ${LETSENCRYPT}
      HTPASS: ${HTPASS}

  database:
    container_name: database
    image: encircle/mariadb:latest
    expose:
      - '3306'
    volumes:
      - ./database/data:/var/lib/mysql
      - ./migrations/:/docker-entrypoint-initdb.d
    networks:
      - backend
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${USER_PASS}
      
  wordpress:
    container_name: wordpress
    image: encircle/wordpress:latest
    expose:
      - '9000'
    depends_on:
      - database
    working_dir: /var/www/html
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - frontend
      - backend
      # - mail
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${USER_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${TABLE_PREFIX}

networks:
  frontend:
  backend:
#    mail:
#      external:
#        name: postfix
