on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: encirclesolutions.azurecr.io
        username: ${{ secrets.acr_encirclesolutions_username }}
        password: ${{ secrets.acr_encirclesolutions_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/images/nginx-modsec" -f  "images/nginx-modsec/Dockerfile" -t encirclesolutions.azurecr.io/wordpresscluster:${{ github.sha }}
        docker push encirclesolutions.azurecr.io/wordpresscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_wordpresscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep wordpressclustere49d | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace wordpressclustere49d`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: wordpressclustere49d
        container-registry-url: encirclesolutions.azurecr.io
        container-registry-username: ${{ secrets.acr_encirclesolutions_username }}
        container-registry-password: ${{ secrets.acr_encirclesolutions_password }}
        secret-name: wordpresscludockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: wordpressclustere49d
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          encirclesolutions.azurecr.io/wordpresscluster:${{ github.sha }}
        imagepullsecrets: |
          wordpresscludockerauth